#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/go
- name: Check if Go is installed
  stat:
    path: "{{ go_install_dir }}/go/bin/go"
  register: go_installed

- name: Download Go tarball
  ansible.builtin.get_url:
    url: "{{ go_tarball_url }}"
    dest: "/tmp/go{{ go_version }}.linux-{{ go_arch }}.tar.gz"
    mode: '0644'
  when: not go_installed.stat.exists

- name: Make go directory
  ansible.builtin.file:
    path: "{{ go_install_dir }}"
    state: directory
  when: not go_installed.stat.exists

- name: Extrair tarball para o diretório de instalação
  ansible.builtin.unarchive:
    src: "/tmp/go{{ go_version }}.linux-{{ go_arch }}.tar.gz"
    dest: "{{ go_install_dir }}/"
    remote_src: true
    owner: root
    group: root
  when: not go_installed.stat.exists

- name: Adiciona o binário go no PATH global
  lineinfile:
    path: /etc/profile.d/go.sh
    line: 'export PATH=$PATH:{{ go_install_dir }}/go/bin'
    create: true
    mode: '0644'
  when: not go_installed.stat.exists
